apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: architecture-demo
spec:
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "auth-config-role"
        vault.hashicorp.com/agent-inject-secret-facebook-auth-config.txt: "secret/facebook_auth_config"
      labels:
        app: auth-api
    spec:
      serviceAccount: vault-service-account
      containers:
      - name: auth-api
        image: architecture_demo/auth-api:v1
        env:
        - name: Database__Name
          value: "auth-db"
        - name: Database__Password
          valueFrom:
            secretKeyRef:
              name: sqlserver-secrets
              key: SA_PASSWORD     
        envFrom:
        - configMapRef:
            name: sqlserver-config
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api
  namespace: architecture-demo
spec:
  type: ClusterIP
  selector:
    app: auth-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
