apiVersion: apps/v1
kind: Deployment
metadata:
  name: architecture_demo/customer-api
  namespace: architecture-demo
spec:
  selector:
    matchLabels:
      app: customer-api
  template:
    metadata:
      labels:
        app: customer-api
    spec:
      containers:
      - name: customer-api
        image: architecture_demo/customer-api:v1
        env:
        - name: DatabaseName
          value: "customer-db"
        - name: DatabasePassword
          valueFrom:
            secretKeyRef:
              name: sqlserver-secrets
              key: SA_PASSWORD     
        envFrom:
        - configMapRef:
          name: sqlserver-config
        - configMapRef:
          name: rabbitmq-config
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: customer-api
  namespace: architecture-demo
spec:
  type: ClusterIP
  selector:
    app: customer-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
