apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
  namespace: architecture-demo
spec:
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - name: order-api
        image: architecture_demo/order-api:v1
        env:
        - name: Database__Name
          value: "order-db"
        - name: Database__Password
          valueFrom:
            secretKeyRef:
              name: sqlserver-secrets
              key: SA_PASSWORD     
        envFrom:
        - configMapRef:
            name: sqlserver-config
        - configMapRef:
            name: rabbitmq-connection-config
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: order-api-service
  namespace: architecture-demo
spec:
  type: ClusterIP
  selector:
    app: order-api-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
