apiVersion: v1
kind: Secret
metadata:
  name: architecture-demo-secrets
  namespace: architecture-demo
stringData:
  SA_PASSWORD: mssQlp4ssword#
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: sqlserver
  namespace: architecture-demo
spec:
  selector:
    matchLabels:
      app: sqlserver-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: sqlserver-pod
    spec:
      containers:
      - name: sqlserver-container
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        volumeMounts:
        - mountPath: "/var/opt/mssql/data"
          name: sqldata-storage
        env:
        - name: "ACCEPT_EULA"
          value: "Y"
        - name: "SA_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: architecture-demo-secrets
              key: SA_PASSWORD 
        - name: "MSSQL_PID"
          value: "Developer"
      volumes:
      - name: sqldata-storage
        persistentVolumeClaim:
          claimName: sqlserver-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
  namespace: architecture-demo
spec:
  selector:
    app: sqlserver-pod
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433