name: frontend
description: Client for Architecture-Demo

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutkit: ^0.0.1
  get_it: ^5.0.1
  provider: ^4.3.2+2
  http: ^0.13.0
  flutter_guid: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - lang/en.json
  - lang/fi.json