apiVersion: v1
kind: PersistentVolume
metadata:
  name: architecture-demo-volume
  namespace: architecture-demo
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"