apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: architecture-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - secretName: ingress-tls-secret
    hosts:
      - "localhost"
  rules:
    - http:
        paths:
        - path: /(.*)
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 80
        - path: /auth-api/(.*)
          pathType: Prefix
          backend:
            service:
              name: auth-api
              port:
                number: 80
        - path: /customer-api/(.*)
          pathType: Prefix
          backend:
            service:
              name: customer-api
              port:
                number: 80
        - path: /order-api/(.*)
          pathType: Prefix
          backend:
            service:
              name: order-api
              port:
                number: 80                 
---
apiVersion: v1
kind: Secret
metadata:
  name: ingress-tls-secret
  namespace: architecture-demo
type: kubernetes.io/tls
data:
  tls.crt: |
        MIIEpDCCAowCCQCSJavbc36mizANBgkqhkiG9w0BAQsFADAUMRIwEAYDVQQDDAlsb2NhbGhvc3QwHhcNMjEwMzEwMDUyOTE0WhcNMjIwMzEwMDUyOTE0WjAUMRIwEAYDVQQDDAlsb2NhbGhvc3QwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCY+EWn5Yg3GayNT5cNPD6QaB/yWg8KnynAIlqse7IjgUws8X/3QOn5bno5zC3O/P2LxHplEC0drapMAQ6lkNbV0zLgE/1ktAimS14bfXUpBhNCUb0iup0Lsvp27yQUfyoO0g5fkQBEOSPwKC3vRkbO3k01EuRCUuziij7U90zH84iUswF3Lzqp64NCHX/wJ1QNamYXh5KMwz6QCt/uoITYUllydSMGr9XRqw25U2piepXBMsmyGHV4lqhxvTgknnde1XlneFL6noSeoG2k04AKeUBfs454mCtT7lFNOwoRTvIYhHXd8zMuQGCT+zAfdzYBU094LiiwDQlDDgPTSiKXDSrD7OliEuz+ankCeTSwuKKt3wBdB8tH6jPBWjoAE2iTKEkZq4obarhvtBD+gXqcyyYiA1l1q2Fv9MsSxglf9qs2lFii9/mF8clXRPNIA9yxp2N7npJoKaJySpYb4i3KslnvFTrzJSvlsVD/ufgI9w+97A1CP+q/aFW/WLGz8R8AKZ4DyT52NlswLGsG2q3hKBolkEM12CwrObqpsFvztjdfq95TrGDAshrACpcmlmUlqRPjWN6bIqZ4c6SJyQVVDX1Xkua7PsX6CcSaqyNL3n1TzYY63NKz8pKCab8W3YzEHKBmYWQ38Dh7mdUrv6HnECfrl2nqiBMrWbv24hLDAQIDAQABMA0GCSqGSIb3DQEBCwUAA4ICAQBaeEQgilnRSgUwiGATxBfHDNAM2rAIwtCnuH3wiVmo3X3AQJsZ/FM/9GWKduJCTFHURr2LO3Oubhj7iR/nmAr0EL3d4A2tflOdtKmwjcdhs46sOww1equZXchxbvxJp5clfVwnJ/eXyJZmJRLZWiz1SGCZCjoPcCT4J89QfUljp+cctv2yuYy4MDjA9BHbn/6X2wi+3KUXPcOuX12sOUw1i8N/RUxA88LZqaPeHcvMT7BdDM0CLaUOqaroq2+UwZ5O6jFQ8GVapskFgwh2wg/xPFnL4NHRqdR6J2V0j/2FRSq0ef+jjP7cOeuC7l1T3ByooTIzR1Akh5GUxSlRrJAxFIhh9KpfR4H7GoiMpINdGw9LAFBFOYUm/Y3C3HJghlaYm7f94LWqbOWDWS7gVKR6E1UO9OFCm4pyUO/YSt+Q4OUOfRb94fiFBbjGPn4LFdVfZMzbnjt44Hrzp0ILxEbGWpyO8jyHn8nrkST9ds0dL7YVZ09SGEgDWchO86l9GLNjqOf6LxdLhGVZWfZoEijppR3ySoGuwlXbgXE3x5s9Nw5DHXj8WXS9V0nrmYqurtMfB8CbAv9pOE6Cye5/DakxD5nbwJ0xejucSghFJM1v+jJzr4wHMIXgUkMW83M6Re8ivX/lK5K+H8KQ033Cx2EBGxM3nyMWn1mI+kFcvkKe5w==
  tls.key: |
        MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQCY+EWn5Yg3GayNT5cNPD6QaB/yWg8KnynAIlqse7IjgUws8X/3QOn5bno5zC3O/P2LxHplEC0drapMAQ6lkNbV0zLgE/1ktAimS14bfXUpBhNCUb0iup0Lsvp27yQUfyoO0g5fkQBEOSPwKC3vRkbO3k01EuRCUuziij7U90zH84iUswF3Lzqp64NCHX/wJ1QNamYXh5KMwz6QCt/uoITYUllydSMGr9XRqw25U2piepXBMsmyGHV4lqhxvTgknnde1XlneFL6noSeoG2k04AKeUBfs454mCtT7lFNOwoRTvIYhHXd8zMuQGCT+zAfdzYBU094LiiwDQlDDgPTSiKXDSrD7OliEuz+ankCeTSwuKKt3wBdB8tH6jPBWjoAE2iTKEkZq4obarhvtBD+gXqcyyYiA1l1q2Fv9MsSxglf9qs2lFii9/mF8clXRPNIA9yxp2N7npJoKaJySpYb4i3KslnvFTrzJSvlsVD/ufgI9w+97A1CP+q/aFW/WLGz8R8AKZ4DyT52NlswLGsG2q3hKBolkEM12CwrObqpsFvztjdfq95TrGDAshrACpcmlmUlqRPjWN6bIqZ4c6SJyQVVDX1Xkua7PsX6CcSaqyNL3n1TzYY63NKz8pKCab8W3YzEHKBmYWQ38Dh7mdUrv6HnECfrl2nqiBMrWbv24hLDAQIDAQABAoICAQCGfQkoswoOf5kQaGBCd6v95D3qIjnFOehIDywvJ1WYF650eSLrrHvJG9OECzpfGFiGUIjXX+B6jlwCFI/fCreHKPc6wPhwWESeh/bGLogaOEgob5rc9LrsNUA13syW5LKCczXF2cMlOCObmofALcZFTHcO6Xwbv7Ka/bZ+IKq1xSxYqATq13A5QmGVeEAqUTl5zgjSORSkg2f21kjJEQGa+tO/aLMRxvgzLbOUM3199Y7CXDeuSAjHq5WO4jCBKX2DuCXTzZsO0t2AZUXguz6AdtgdC81/wzGcyhNa1kRksUbyPUsvhwmBaYI/uIE3uOSXR7q/y71kAyIYfTLpye0cCrRlQ7qF4vTMcy8c45DYnjtbZ821HqoEDwTze3C82JjsGoPosc0mp8ps75FB4AlKyh+LApmOYvfbmwCHaiE2xnWpkMlaqJTp+l2ce+xJLG5EewuFEvUB7WYD8INtRxyAB1RSoOyFMo5ECEjEYnnDkQ+UZwpntWeIMGj4sLEZw6F7GFPqFGcqQWorEtVj5ISN7A3bOUr2W2n1YoQM7qFchmWcn7s5qC4nGaO4e3dwyhScHPrWDJp43zCNIDmRvpbEHlrwCYoxRCo61KclH/mV1JJNr+xPBSacrawVHY0AZYp0X/c0CwH0xcTjnqdnPNp0d3SG4mHKkfKk1UffnJwfPQKCAQEAxoZCnmTzz2QUNKSGq0FKAkrfi84Y0G8iQsJKgc8sORPwICGG38b3qziC7/6lcxqeFBy/q0ELRd5StNjcf01tuh5ljIp9NOOIeADGpv6L4ycX8XmapVBSrMSdDh8lTEfdyC8GIuUXw5+wG9K7XHrRA/WNawF/LjGUXB3MCxMvioE7StJuAWzFPM+HuFzCwSa/NRuPjtv6URDWJrwW90hHwxAbRhEZxRL/DqOYQKBm3CoGbd5b9fl2K1tlB5MDe3ps5FuofaiJ5oWYpDXdP4fXqicZcsNOUrUixiChc27er3moGUE7iVYTPoF+XnRuuHUpwbbl0s7aigNtBIr3gfuZqwKCAQEAxUG065T9zQ4oc7j/v8LWsVlkyko250dyz4lfxpPn848Sfaz+wdZbodDYlyJwOZh1BnU29A8m7XUUrg5OvIYMg4UwFOLAh3DYuN8C8iEWtUInitxyeGA3e88yP2L1GWS+xm+Ew+axbhsem1vd1V+VbR1ffqXIjX6n6vv/FB59oGH/tH+Ab2BG4x/Xr8fXcVCP3sen+yobioR/n1wJwHSQP7kbnTFlVzpIFYESVTvbu9L+2ALMfY4atWpTjZeS6U+pOtLB0SBpjkM4M7GywbRe+slMyZZMiFAzNTGySS3IO3ZFzCpIVMGfdZkt9KeJqV8brPmLfR18gAEdHXyT2mXiAwKCAQBW0RgJFLTamTWM3/ZUpjSrU/r2tKZ9YFxnPXg/1E3OmD2Gj6Lf8a8VnZ0FPyMzdwxyVzAqwEMhxtv8Ymnq8f1uSyS1lUqz+l0PvaciGGcsa0g5Pai3aqz9CO514oD5HuSKSqYwVGdUEV1+jWWKR9toE9ZIWVs45E2xCwbUQQulUmaPjf61eM+4jDkaEtbIiR1NKERbgS+yi95bCh4w/dcEIuMKfSf72xbXXAuVF5Bj76zoFzm4E+PtigZgjZYURbGhG8RPT4ke2oWqKjQbOFjD/F1QpsB1wuj2JAb26CFSM62jfbd/k7jOuOp+fAR/fh1IradLzVIc0Oq39d3PZiwJAoIBABfbKHxNWpyQF8hXGWchs0FjpFLqwtUZyQLchF7JyIWmSgA1CeJ7gD2Duo4ctiHhFFYhmvHNW1HglQ2v4UnflGfblcMQ4WP/+9Xv8rVB1zM4uvuKSbXRPSSWHGeaGjZl/sSU/CONJOxCD2OOqreBhdracJAqkKS8Kqa6r1DJlzvsXjaALRJLPId/dGBn9OBZc+znjKNNpmMMPzsQsIU8E64BPxu1u6HfBJTFNWhlgt+mVvfc7spIg2ZpY41+RWA+KCNbFeGq39k6u/NUjF/s5ofCDK1cpgjeWjMWvY8oIE1AspRMkM7fU9+vFOW/1WBMhlZXH82T4VjBybmlNWR2ae0CggEATdSTkk7+2AOWtCyqVkPQcoFLQIyVEZn2doLMqlOit3+behIu0UZM3jPKSORmw8BggOA5h+bZDkxupVEFNkja0R7Oj8xbcRhFE4XNv9l/cTVDeNkdIFCOD0EDM6p1KnjLV8Ck4t+KgcMCbwzPnoHwisRRD9CSUsfmhU8+W2yWNiqyIMNi+rKkKDHwGThyPZ7LX9sDmXMzXIstqvkew7XnCCb6qTQDEUxbOGHU7QaglM9kL+OM3Jday6uo4SrrjVaaVQvFeH83u15HbVZub1bQ7e/nq/p9B6v5Jd5tuwFpRvhKQo3XyF5rL8x1ukTKbZXT9BFNlalSsg/Gj0gDa7fy7A==