apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api-deployment
  namespace: architecture-demo
spec:
  selector:
    matchLabels:
      app: order-api-pod
  template:
    metadata:
      labels:
        app: order-api-pod
    spec:
      containers:
      - name: order-api-container
        image: architecture_demo/order-api:v1
        env:
          - name: DatabaseServer
            value: "sqlserver-service"
          - name: DatabaseName
            value: "order-db" 
          - name: DatabasePort
            value: "1433"
          - name: DatabaseUser
            value: "sa"
          - name: DatabasePassword
            valueFrom:
              secretKeyRef:
                name: architecture-demo-secrets
                key: SA_PASSWORD            
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: order-api-service
  namespace: architecture-demo
spec:
  type: ClusterIP
  selector:
    app: order-api-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
