apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq
  namespace: architecture-demo
spec:
  serviceName: rabbitmq
  replicas: 1
  selector:
    matchLabels:
      component: rabbitmq
  template:
    metadata:
      labels:
        app: taskQueue
        component: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3-management
        name: rabbitmq
        env:
        - name: RABBITMQ_DEFAULT_PASS
          value: "guest"
        - name: RABBITMQ_DEFAULT_USER
          value: "guest"
        ports:
          - name: http
            protocol: TCP
            containerPort: 15672
          - name: amqp
            protocol: TCP
            containerPort: 5672
          - name: epmd
            containerPort: 4369
        resources:
          limits:
            cpu: 100m
        imagePullPolicy: Always
      
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management-service
  namespace: architecture-demo
  labels:
    component: rabbitmq
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      targetPort: 15672
      name: http
  selector:
    component: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: architecture-demo
  labels:
    component: rabbitmq
spec:
  type: ClusterIP
  ports:
  - port: 5672
  selector:
    app: taskQueue
    component: rabbitmq