apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-deployment
  namespace: architecture-demo
spec:
  selector:
    matchLabels:
      app: service-b-pod
  template:
    metadata:
      labels:
        app: service-b-pod
    spec:
      containers:
      - name: service-b-container
        image: majamakm/service-b:v1
        env:
          - name: DatabaseServer
            value: "sqlserver-service"
          - name: DatabasePort
            value: "1433"
          - name: DatabaseUser
            value: "sa"
          - name: DatabasePassword
            valueFrom:
              secretKeyRef:
                name: secrets
                key: SA_PASSWORD 
          - name: DatabaseName
            value: "service-b"            
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: architecture-demo
spec:
  type: NodePort
  selector:
    app: service-b-pod
  ports:
  - port: 80
    targetPort: 80
