apiVersion: apps/v1
kind: Deployment
metadata:
  name: architecture-demo-deployment
  namespace: architecture-demo
spec:
  selector:
    matchLabels:
      app: service-a-pod
  template:
    metadata:
      labels:
        app: service-a-pod
    spec:
      containers:
      - name: service-a-container
        image: majamakm/service-a:v1
        env:
          - name: ASPNETCORE_ENVIROMENT
            value: DEVELOPMENT
          - name: SQLSERVER_CONNECTIONSTRING
            value: "Server=localhost:30002;Database=myapp;User=sa;Password=Password_123;MultipleActiveResultSets=true;"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
