kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sqlserver-pvc
  namespace: architecture-demo
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi